# https://golangci-lint.run/usage/configuration/
version: "2"
linters:
    default: standard
    exclusions:
        generated: lax
        presets:
            - comments
            - common-false-positives
            - legacy
            - std-error-handling
        paths:
            - third_party$
            - builtin$
            - examples$
            - assets$
            - codegen
formatters:
    exclusions:
        generated: lax
        paths:
            - third_party$
            - builtin$
            - examples$
            - assets$
            - codegen$
    enable:
        - gci
        - gofmt
        - gofumpt
        - goimports
        - golines
        - swaggo
