debug: true
enableSwagger: true

pprof:
  account: { admin: "admin" }

app:
  name: "MyApp"
  version: "1.0.0"

logger:
  system:
    level: info
    writer: os
    settings: { name: stdout }
  web:
    level: info
    writer: os
    settings: { name: stdout }

sentry:
  enable: false
  dsn: ""

auth:
  bearerToken: "xxx"

databases:
  - id: "default"
    host: "localhost"
    port: 3306
    user: "root"
    password: ""
    name: "xgo"
    maxOpenConns: 200
    maxIdleConns: 50
    connMaxLifetimeSecond: 600
    debugMode: false

server:
  service:
    - name: default
      port: 8080
      graceTimeout: 30
      ginRunMode: debug

      log:
          level: info
          ForceToStdout: true

      # 用户访问限制
      allowedUsers: []
      # 健康检查
      healthz:
          token: <masked>
      # 指标上报
      metric:
          token: <masked>
