app:
  name: "MyApp"
  version: "1.0.0"

logger:
  system:
    level: info
    writer: os
    settings: { name: stdout }
  web:
    level: info
    writer: os
    settings: { name: stdout }

sentry:
  enable: false
  dsn: ""
