package watch

import "github.com/fengzhongzhu1621/xgo/ginx/apps/cmdb/resource_watch/stream"

type ChainNode struct {
	// self increasing id, used for sequential batch query
	ID uint64 `json:"id" bson:"id"`
	// event's cluster time
	ClusterTime stream.TimeStamp `json:"cluster_time" bson:"cluster_time"`
	// event's document object id, as is the value of "_id" in a document.
	Oid string `json:"oid" bson:"oid"`
	// event's type
	EventType EventType `json:"type" bson:"type"`
	// event's resume token, if token is "", then it's a head, and no tail
	Token string `json:"token" bson:"token"`
	// generated by cmdb, and is 1:1 with mongodb's resume token
	// the current node's cursor
	Cursor string `json:"cursor" bson:"cursor"`
	// InstanceID object instance's ID, preserved for latter event aggregation operation
	InstanceID int64 `json:"inst_id,omitempty" bson:"inst_id,omitempty"`
	// SubResource the sub resource of the watched resource, eg. the object ID of the instance resource
	SubResource []string `json:"bk_sub_resource,omitempty" bson:"bk_sub_resource,omitempty"`
	// SupplierAccount the supplier account of the chain node's related event resource.
	SupplierAccount string `json:"bk_supplier_account" bson:"bk_supplier_account"`
}

type LastChainNodeData struct {
	Coll        string           `json:"_id" bson:"_id"`
	ID          uint64           `json:"id" bson:"id"`
	Token       string           `json:"token" bson:"token"`
	Cursor      string           `json:"cursor" bson:"cursor"`
	StartAtTime stream.TimeStamp `json:"start_at_time,omitempty" bson:"start_at_time,omitempty"`
}
