// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: helloworld.proto

// trpc.{app}.{server}，以 trpc 为固定前缀，标识这是一个 trpc 服务协议
// app 是应用名
// server 是服务进程名
// 生成的trpc_go.yaml中包含
//
// server:  # Server configuration.
//   app: examples  # Application name for the business.
//   server: helloworld  # Process server name.
//   service:  # Services provided by the business, can have multiple.
//     # 路由标识 trpc.{app}.{server}.{service}
//     - name: trpc.examples.helloworld.Greeter  # Route name for the service.

package helloworld

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "trpc.group/trpc/trpc-protocol/pb/go/trpc/api"
	_ "trpc.group/trpc/trpc-protocol/pb/go/trpc/proto"
	_ "trpc.group/trpc/trpc-protocol/pb/go/trpc/validate"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_helloworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_helloworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetMessageRequest1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Mapped to URL path.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest1) Reset() {
	*x = GetMessageRequest1{}
	mi := &file_helloworld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest1) ProtoMessage() {}

func (x *GetMessageRequest1) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest1.ProtoReflect.Descriptor instead.
func (*GetMessageRequest1) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessageRequest1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Message1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // The resource content.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message1) Reset() {
	*x = Message1{}
	mi := &file_helloworld_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message1) ProtoMessage() {}

func (x *Message1) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message1.ProtoReflect.Descriptor instead.
func (*Message1) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{3}
}

func (x *Message1) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetMessageRequest2 struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	MessageId     string                         `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Mapped to URL path.
	Revision      int64                          `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`                   // Mapped to URL query parameter `revision`.
	Sub           *GetMessageRequest2_SubMessage `protobuf:"bytes,3,opt,name=sub,proto3" json:"sub,omitempty"`                              // Mapped to URL query parameter `sub.subfield`.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest2) Reset() {
	*x = GetMessageRequest2{}
	mi := &file_helloworld_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest2) ProtoMessage() {}

func (x *GetMessageRequest2) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest2.ProtoReflect.Descriptor instead.
func (*GetMessageRequest2) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessageRequest2) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetMessageRequest2) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *GetMessageRequest2) GetSub() *GetMessageRequest2_SubMessage {
	if x != nil {
		return x.Sub
	}
	return nil
}

type Message2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // The resource content.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message2) Reset() {
	*x = Message2{}
	mi := &file_helloworld_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message2) ProtoMessage() {}

func (x *Message2) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message2.ProtoReflect.Descriptor instead.
func (*Message2) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{5}
}

func (x *Message2) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UpdateMessageRequest3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // mapped to the URL
	Message       *Message3              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // mapped to the body
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageRequest3) Reset() {
	*x = UpdateMessageRequest3{}
	mi := &file_helloworld_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageRequest3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageRequest3) ProtoMessage() {}

func (x *UpdateMessageRequest3) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageRequest3.ProtoReflect.Descriptor instead.
func (*UpdateMessageRequest3) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMessageRequest3) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *UpdateMessageRequest3) GetMessage() *Message3 {
	if x != nil {
		return x.Message
	}
	return nil
}

type Message3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // The resource content.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message3) Reset() {
	*x = Message3{}
	mi := &file_helloworld_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message3) ProtoMessage() {}

func (x *Message3) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message3.ProtoReflect.Descriptor instead.
func (*Message3) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{7}
}

func (x *Message3) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Message4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message4) Reset() {
	*x = Message4{}
	mi := &file_helloworld_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message4) ProtoMessage() {}

func (x *Message4) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message4.ProtoReflect.Descriptor instead.
func (*Message4) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{8}
}

func (x *Message4) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message4) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetMessageRequest5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest5) Reset() {
	*x = GetMessageRequest5{}
	mi := &file_helloworld_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest5) ProtoMessage() {}

func (x *GetMessageRequest5) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest5.ProtoReflect.Descriptor instead.
func (*GetMessageRequest5) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{9}
}

func (x *GetMessageRequest5) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetMessageRequest5) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Message5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // The resource content.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message5) Reset() {
	*x = Message5{}
	mi := &file_helloworld_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message5) ProtoMessage() {}

func (x *Message5) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message5.ProtoReflect.Descriptor instead.
func (*Message5) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{10}
}

func (x *Message5) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetMessageRequest2_SubMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subfield      string                 `protobuf:"bytes,1,opt,name=subfield,proto3" json:"subfield,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest2_SubMessage) Reset() {
	*x = GetMessageRequest2_SubMessage{}
	mi := &file_helloworld_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest2_SubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest2_SubMessage) ProtoMessage() {}

func (x *GetMessageRequest2_SubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest2_SubMessage.ProtoReflect.Descriptor instead.
func (*GetMessageRequest2_SubMessage) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetMessageRequest2_SubMessage) GetSubfield() string {
	if x != nil {
		return x.Subfield
	}
	return ""
}

var File_helloworld_proto protoreflect.FileDescriptor

const file_helloworld_proto_rawDesc = "" +
	"\n" +
	"\x10helloworld.proto\x12\x18trpc.examples.helloworld\x1a\x1ctrpc/validate/validate.proto\x1a\x1dtrpc/proto/trpc_options.proto\x1a\x1atrpc/api/annotations.proto\")\n" +
	"\fHelloRequest\x12\x19\n" +
	"\x03msg\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03msg\"\x1e\n" +
	"\n" +
	"HelloReply\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"(\n" +
	"\x12GetMessageRequest1\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1e\n" +
	"\bMessage1\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xc4\x01\n" +
	"\x12GetMessageRequest2\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\x12I\n" +
	"\x03sub\x18\x03 \x01(\v27.trpc.examples.helloworld.GetMessageRequest2.SubMessageR\x03sub\x1a(\n" +
	"\n" +
	"SubMessage\x12\x1a\n" +
	"\bsubfield\x18\x01 \x01(\tR\bsubfield\"\x1e\n" +
	"\bMessage2\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"t\n" +
	"\x15UpdateMessageRequest3\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12<\n" +
	"\amessage\x18\x02 \x01(\v2\".trpc.examples.helloworld.Message3R\amessage\"\x1e\n" +
	"\bMessage3\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"=\n" +
	"\bMessage4\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"L\n" +
	"\x12GetMessageRequest5\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x1e\n" +
	"\bMessage5\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2w\n" +
	"\aGreeter\x12l\n" +
	"\bSayHello\x12&.trpc.examples.helloworld.HelloRequest\x1a$.trpc.examples.helloworld.HelloReply\"\x12\x8a\xb5\x18\x0e/cgi-bin/hello2{\n" +
	"\vGreeterHttp\x12l\n" +
	"\bSayHello\x12&.trpc.examples.helloworld.HelloRequest\x1a$.trpc.examples.helloworld.HelloReply\"\x12\x8a\xb5\x18\x0e/cgi-bin/hello2\x90\x01\n" +
	"\x11Messaging1Restful\x12{\n" +
	"\n" +
	"GetMessage\x12,.trpc.examples.helloworld.GetMessageRequest1\x1a\".trpc.examples.helloworld.Message1\"\x1b\xca\xc1\x18\x17\x12\x15/v1/{name=messages/*}2\x94\x01\n" +
	"\x11Messaging2Restful\x12\x7f\n" +
	"\n" +
	"GetMessage\x12,.trpc.examples.helloworld.GetMessageRequest2\x1a\".trpc.examples.helloworld.Message2\"\x1f\xca\xc1\x18\x1b\x12\x19/v1/messages/{message_id}2\xa4\x01\n" +
	"\x11Messaging3Restful\x12\x8e\x01\n" +
	"\rUpdateMessage\x12/.trpc.examples.helloworld.UpdateMessageRequest3\x1a\".trpc.examples.helloworld.Message3\"(\xca\xc1\x18$:\amessage\"\x19/v1/messages/{message_id}2\x90\x01\n" +
	"\x11Messaging4Restful\x12{\n" +
	"\rUpdateMessage\x12\".trpc.examples.helloworld.Message4\x1a\".trpc.examples.helloworld.Message4\"\"\xca\xc1\x18\x1e:\x01*\"\x19/v1/messages/{message_id}2\xc2\x01\n" +
	"\x11Messaging5Restful\x12\xac\x01\n" +
	"\n" +
	"GetMessage\x12,.trpc.examples.helloworld.GetMessageRequest5\x1a\".trpc.examples.helloworld.Message5\"L\xca\xc1\x18HZ+\x12)/v1/users/{user_id}/messages/{message_id}\x12\x19/v1/messages/{message_id}B>Z<github.com/fengzhongzhu1621/xgo/trpc/trpcprotocol/helloworldb\x06proto3"

var (
	file_helloworld_proto_rawDescOnce sync.Once
	file_helloworld_proto_rawDescData []byte
)

func file_helloworld_proto_rawDescGZIP() []byte {
	file_helloworld_proto_rawDescOnce.Do(func() {
		file_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_proto_rawDesc), len(file_helloworld_proto_rawDesc)))
	})
	return file_helloworld_proto_rawDescData
}

var file_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_helloworld_proto_goTypes = []any{
	(*HelloRequest)(nil),                  // 0: trpc.examples.helloworld.HelloRequest
	(*HelloReply)(nil),                    // 1: trpc.examples.helloworld.HelloReply
	(*GetMessageRequest1)(nil),            // 2: trpc.examples.helloworld.GetMessageRequest1
	(*Message1)(nil),                      // 3: trpc.examples.helloworld.Message1
	(*GetMessageRequest2)(nil),            // 4: trpc.examples.helloworld.GetMessageRequest2
	(*Message2)(nil),                      // 5: trpc.examples.helloworld.Message2
	(*UpdateMessageRequest3)(nil),         // 6: trpc.examples.helloworld.UpdateMessageRequest3
	(*Message3)(nil),                      // 7: trpc.examples.helloworld.Message3
	(*Message4)(nil),                      // 8: trpc.examples.helloworld.Message4
	(*GetMessageRequest5)(nil),            // 9: trpc.examples.helloworld.GetMessageRequest5
	(*Message5)(nil),                      // 10: trpc.examples.helloworld.Message5
	(*GetMessageRequest2_SubMessage)(nil), // 11: trpc.examples.helloworld.GetMessageRequest2.SubMessage
}
var file_helloworld_proto_depIdxs = []int32{
	11, // 0: trpc.examples.helloworld.GetMessageRequest2.sub:type_name -> trpc.examples.helloworld.GetMessageRequest2.SubMessage
	7,  // 1: trpc.examples.helloworld.UpdateMessageRequest3.message:type_name -> trpc.examples.helloworld.Message3
	0,  // 2: trpc.examples.helloworld.Greeter.SayHello:input_type -> trpc.examples.helloworld.HelloRequest
	0,  // 3: trpc.examples.helloworld.GreeterHttp.SayHello:input_type -> trpc.examples.helloworld.HelloRequest
	2,  // 4: trpc.examples.helloworld.Messaging1Restful.GetMessage:input_type -> trpc.examples.helloworld.GetMessageRequest1
	4,  // 5: trpc.examples.helloworld.Messaging2Restful.GetMessage:input_type -> trpc.examples.helloworld.GetMessageRequest2
	6,  // 6: trpc.examples.helloworld.Messaging3Restful.UpdateMessage:input_type -> trpc.examples.helloworld.UpdateMessageRequest3
	8,  // 7: trpc.examples.helloworld.Messaging4Restful.UpdateMessage:input_type -> trpc.examples.helloworld.Message4
	9,  // 8: trpc.examples.helloworld.Messaging5Restful.GetMessage:input_type -> trpc.examples.helloworld.GetMessageRequest5
	1,  // 9: trpc.examples.helloworld.Greeter.SayHello:output_type -> trpc.examples.helloworld.HelloReply
	1,  // 10: trpc.examples.helloworld.GreeterHttp.SayHello:output_type -> trpc.examples.helloworld.HelloReply
	3,  // 11: trpc.examples.helloworld.Messaging1Restful.GetMessage:output_type -> trpc.examples.helloworld.Message1
	5,  // 12: trpc.examples.helloworld.Messaging2Restful.GetMessage:output_type -> trpc.examples.helloworld.Message2
	7,  // 13: trpc.examples.helloworld.Messaging3Restful.UpdateMessage:output_type -> trpc.examples.helloworld.Message3
	8,  // 14: trpc.examples.helloworld.Messaging4Restful.UpdateMessage:output_type -> trpc.examples.helloworld.Message4
	10, // 15: trpc.examples.helloworld.Messaging5Restful.GetMessage:output_type -> trpc.examples.helloworld.Message5
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_helloworld_proto_init() }
func file_helloworld_proto_init() {
	if File_helloworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_proto_rawDesc), len(file_helloworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_helloworld_proto_goTypes,
		DependencyIndexes: file_helloworld_proto_depIdxs,
		MessageInfos:      file_helloworld_proto_msgTypes,
	}.Build()
	File_helloworld_proto = out.File
	file_helloworld_proto_goTypes = nil
	file_helloworld_proto_depIdxs = nil
}
