// Code generated by MockGen. DO NOT EDIT.
// Source: test.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMyInterForMock is a mock of MyInterForMock interface.
type MockMyInterForMock struct {
	ctrl     *gomock.Controller
	recorder *MockMyInterForMockMockRecorder
}

// MockMyInterForMockMockRecorder is the mock recorder for MockMyInterForMock.
type MockMyInterForMockMockRecorder struct {
	mock *MockMyInterForMock
}

// NewMockMyInterForMock creates a new mock instance.
func NewMockMyInterForMock(ctrl *gomock.Controller) *MockMyInterForMock {
	mock := &MockMyInterForMock{ctrl: ctrl}
	mock.recorder = &MockMyInterForMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMyInterForMock) EXPECT() *MockMyInterForMockMockRecorder {
	return m.recorder
}

// GetName mocks base method.
func (m *MockMyInterForMock) GetName(id int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName", id)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockMyInterForMockMockRecorder) GetName(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockMyInterForMock)(nil).GetName), id)
}

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDB) Get(key string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDBMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDB)(nil).Get), key)
}
